export default [
  {
    id: 'OOPAndInheritanceAssignment',
    name: 'OOP And Inheritance Assignment',
    tags: ['Java', 'School Work'],
    github: 'https://github.com/ggggg/Algorithms-Assignment',
    description: 'An assignment showcasing OOP fetures in Java for computer science 12 course.',
  },
  {
    id: 'BPEssentials',
    name: 'BP Essentials',
    contributors: ['PLASMAchicken', 'UserR00T'],
    github: 'https://github.com/BPEssentials/Core',
    tags: ['C#', 'Broke Protocol'],
    description: 'BP:Essentials (also known as BPE) is a Broke Protocol plugin used by server owners to make it easier to moderate their server. BPE Also has some commands for players like /kits and /warps, so for everyone there is something you can use. 56 commands defined, and counting. <br/> See <a href="https://bpessentials.github.io/Docs/" target="_blank">BPE website</a>',
  },
  {
    id: 'SwingNavigator',
    name: 'Java Swing Navigator',
    tags: ['Java', 'School Work'],
    github: 'https://github.com/ggggg/SwingNavigator',
    description: 'Java screen manager library for the java swing lib, allowing for easy naviation.',
  },
  {
    id: 'BpTheGpvp',
    name: 'Broke Protocol PvP Plugin',
    tags: ['C#', 'Broke Protocol'],
    private: true,
    description: 'A plugin allowing player vs player fights in the game Broke Protocol.',
  },
  {
    id: 'AlgorithmsAssignment',
    name: 'Java Algorithms Assignment',
    tags: ['Java', 'School Work'],
    github: 'https://github.com/ggggg/Algorithms-Assignment',
    description: 'A utills class full of usfull algorithms made in Java for computer science 12 course.',
  },
  {
    id: 'PlWebsiteShop',
    name: 'Pointlife Website + Shop',
    tags: ['JavaScript', 'Broke Protocol', 'VueJs', 'NodeJs', 'HTML'],
    private: true,
    contributors: ['PLASMAchicken', 'SinedxGames'],
    description: 'A website connected to the Pointlife Broke Protocol server that allows users to purchase ranks, look for users, and view their info. <br> <a href="https://pointlife.net" target="_blank">Pointlife Website</a>',
  },
  {
    id: 'UTSC-cs12',
    name: 'Unoffical University of Toronto Scarborough Computer Science Website.',
    tags: ['HTML', 'School Work'],
    github: 'https://github.com/ggggg/UTSC-cs12',
    description: 'A site showcasing University of Toronto Scarborough\'s Computer Science program made in HTML for computer science 12 course. <br><a href="https://ggggg.github.io/UTSC-cs12/" target="_blank">Click here to view the site.</a>',
  },
  {
    id: 'ppcwebpanel',
    name: 'PPC Webpanel Bot + REST API',
    tags: ['JavaScript', 'Broke Protocol', 'NodeJs', 'Discord'],
    private: true,
    contributors: ['PLASMAchicken'],
    description: 'A discord bot connected to the Pointlife Broke Protocol server that allows users to report users, view their info, in addtion to that it also allows staff to modrate the server with the discord interface.',
  },
  {
    id: 'DinoGame',
    name: 'Java Dino Game',
    tags: ['Java', 'School Work'],
    github: 'https://github.com/ggggg/Java-dino-game',
    description: 'A simple and fun game made in Java for computer science 11 course.',
  },
  {
    id: 'Ghooks',
    name: 'Ghooks',
    tags: ['C#', 'Broke Protocol', 'Discord'],
    github: 'https://github.com/ggggg/Ghooks',
    contributors: ['xiluisx'],
    description: 'Broke Protocol discord connection plugin allowing server owners to send messages to their discord servers when certin events are triggered.',
  },
  {
    id: 'PythonAssignment',
    name: 'Python Assignment',
    tags: ['Python', 'School Work'],
    github: 'https://github.com/ggggg/PythonAssignment-',
    description: 'Introductory python assignment for computer science 12.',
  },
  {
    id: 'JavaTaskManager',
    name: 'Java Task Manager',
    tags: ['Java'],
    github: 'https://github.com/ggggg/Java-Task-Manager',
    description: 'Simple task manager made in java.',
  },
  {
    id: '1MinToDo',
    name: '1MinToDo',
    tags: ['React', 'React Native', 'NodeJs', 'JavaScript'],
    private: true,
    contributors: ['razprofile'],
    description: 'ToDo mobile app made in react native.',
  },
  {
    id: 'VirusTotalBot',
    name: 'Virus Total Bot',
    private: true,
    tags: ['NodeJs', 'Discord', 'JavaScript'],
    description: 'Unofficial antivirus discord bot made using Virustotal\'s v3 API, made to scan links, files, and attachments. <br> See <a href="https://top.gg/bot/790032946425364510" target="_blank">Top.gg bot listing</a>',
  },
  {
    id: 'BankSim',
    name: 'Bank Simulator',
    github: 'https://github.com/ggggg/BankSim',
    tags: ['Java', 'School Work'],
    description: 'A bank progarm made in Java and uses MongoDB database.<br>Made part of Computer Science 12 course.',
  },
];
